# Site/SEO settings
email: csiddu98@gmail.com
baseurl: "/portfolio"
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Siddharth Chatla
title: portfolio
description: >
  List of my ongoing work and interests.
url: http://chatla-siddharth.github.io
#twitter_username: thomasvaeth
default_img: /assets/images/seo.jpg
social:
# - name: twitter
#    url: https://twitter.com/thomasvaeth
  - name: instagram
    url: https://www.instagram.com/siddharth98_uchiha/
  - name: linkedin
    url: https://www.linkedin.com/in/siddarth-chatla-a71664133/
  - name: github
    url: https://github.com/chatla-siddharth
#  - name: codepen
#    url: https://codepen.io/thomasvaeth/

# Contact settings
#contact_img: /assets/images/placeholder-28.jpg
#formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
#disqus: test-apkdzgmqhj

# MailChimp settings
#mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
#mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Siddharth Chatla
    bio: Siddharth was born in hyderbad. He is a student at GCET.
    url: https://chatla-siddharth.github.io/portfolio/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
