---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: layout
  label: layout
  description: layout of the post
  default: post
- type: text
  label: title
  name: title
  description: title of the post
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: file
  name: image
  label: image
- type: text
  name: author
  label: author
  default: SIDDHARTH
- type: tag_list
  name: tags
  label: tags
pages:
- _posts/2019-01-14-water-color.md
- _posts/2019-01-14-bleeding-black.md
- _posts/2019-01-14-focus-colour.md
- _posts/2019-01-15-no-face-sam.md
- _posts/2019-01-15-joker-s-mask.md
- _posts/2019-01-15-masked-neo.md
- _posts/2019-01-15-rise-rose.md
- _posts/2019-01-15-fly.md
- _posts/2019-01-15-marine.md
- _posts/2019-01-16-vamp.md
- _posts/2019-01-16-hollow-skulll.md
- _posts/2019-01-16-elder-wand.md
- _posts/2019-01-16-thinking-zen.md
- _posts/wolverine.md
